#-------------------------------
# General Site Settings
title: Montse Cebrian
logo: # You can add own logo. For example '/images/logo.png'.
description: Montse Cebrian personal site. Project Management. Program Management. Short Stories.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.montsecebrian.net" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Montse Cebrian
  image: '/images/avatar_montse.jpg'
  avatar: '/images/avatar_montse.jpg'
  description: Born in Barcelona, then adopted by New York. Pop Culture fiend, never foe. I manage technical programs and write a Pop Culture and Project Management newsletter. Check my experience on LinkedIn and subscribe to my newsletter through the paper plane icon below.


#-------------------------------
# Contact links

# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
contact:
- {name: "Twitter", icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/montsecebrian/"}
- {name: "Substack", icon: "ion-md-paper-plane", link: "https://popcultureguidetopm.substack.com/"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp-description: Subscribe to our newsletter and we’ll send you the emails of latest posts.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed